spring:
    application:
        name: front-application

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}