spring:
    application:
        name: backend-service
    cloud:
        config:
            enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    metadataMap:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


---
spring:
    profiles: instance1
server:
    port: 9000

---
spring:
    profiles: instance2
server:
    port: 9001

